-- workflow_tasks was missing the requires_legal_verification flag that
-- lib/corporate-events/rules.ts already defines per task template (e.g. the
-- SECP filing task generated by a director resignation). generateWorkflow()
-- silently dropped it on insert, so the landing page's FAQ claim that these
-- tasks get flagged wasn't actually true — the description text mentioned
-- "not verified" but there was no queryable flag or badge.
alter table workflow_tasks
  add column requires_legal_verification boolean not null default false;
